services:
  frontend:
    # Keep your existing settings
    networks:
      default: {}
      mhealth:
        aliases:
          - ecommerce-frontend

  backend:
    # Keep your existing settings
    networks:
      default: {}
      mhealth:
        aliases:
          - ecommerce-backend

networks:
  default:
  mhealth:
    external: true
    name: mhealth_default
