services:
  backend:
    image: ghcr.io/mariosmpratsos/ecommerce-backend:latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  frontend:
    image: ghcr.io/mariosmpratsos/ecommerce-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
